{% set name = "sarsen" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a17b4acc8166b566fbd86d3f5e105c2a089caea5f6b67eda9df0bf69844beeb5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sarsen = sarsen.__main__:app

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - attrs
    - click
    - numpy
    - python >=3.8
    - rioxarray
    - scipy
    - typer
    - xarray >=2022.06.0
    - xarray-sentinel >=0.9.3

test:
  imports:
    - sarsen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sarsen/
  summary: Algorithms and utilities for Synthetic Aperture Radar (SAR) sensors
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - aurghs
    - alexamici
